workflow testing

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -134,89 +134,89 @@ jobs:
           docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
           echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
 
-      - name: Run Trivy vulnerability scanner in docker mode
-        uses: aquasecurity/trivy-action@master
-        with:
-            image-ref: ${{ steps.build-image.outputs.image }}
-            format: 'table'
-            severity: 'HIGH,CRITICAL'
-            vuln-type: 'os,library'
-            exit-code: 1
-            ignore-unfixed: true
-        continue-on-error: true
+      # - name: Run Trivy vulnerability scanner in docker mode
+      #   uses: aquasecurity/trivy-action@master
+      #   with:
+      #       image-ref: ${{ steps.build-image.outputs.image }}
+      #       format: 'table'
+      #       severity: 'HIGH,CRITICAL'
+      #       vuln-type: 'os,library'
+      #       exit-code: 1
+      #       ignore-unfixed: true
+      #   continue-on-error: true
 
-      - name: Push image to Amazon ECR
-        id: push-image
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          IMAGE_TAG: ${{ steps.prep.outputs.BUILD_ID }}
-          LATEST_ID: ${{ steps.prep.outputs.LATEST_ID }}
-        run: |
-          # push image to aws ecr
-          docker push $ECR_REPOSITORY:$IMAGE_TAG
-          echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+      # - name: Push image to Amazon ECR
+      #   id: push-image
+      #   env:
+      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #     IMAGE_TAG: ${{ steps.prep.outputs.BUILD_ID }}
+      #     LATEST_ID: ${{ steps.prep.outputs.LATEST_ID }}
+      #   run: |
+      #     # push image to aws ecr
+      #     docker push $ECR_REPOSITORY:$IMAGE_TAG
+      #     echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
 
-      - name: Fill in the new image ID in the Amazon ECS task definition
-        id: task-def
-        uses: aws-actions/amazon-ecs-render-task-definition@v1
-        with:
-          task-definition: ${{ env.ECS_TASK_DEFINITION }}
-          container-name: ${{ env.CONTAINER_NAME }}
-          image: ${{ steps.push-image.outputs.image }}
-          environment-variables: |
-            ENVIRONMENT=${{ env.ENVIRONMENT }}
-            HOST=${{ vars.HOST }} 
-            PORT=${{ vars.PORT }} 
-            ELASTIC_URL=${{ vars.ELASTIC_URL }} 
-            ELASTIC_KEY=${{ vars.ELASTIC_KEY }}
-            IMAGE=${{ steps.push-image.outputs.image }}
+      # - name: Fill in the new image ID in the Amazon ECS task definition
+      #   id: task-def
+      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
+      #   with:
+      #     task-definition: ${{ env.ECS_TASK_DEFINITION }}
+      #     container-name: ${{ env.CONTAINER_NAME }}
+      #     image: ${{ steps.push-image.outputs.image }}
+      #     environment-variables: |
+      #       ENVIRONMENT=${{ env.ENVIRONMENT }}
+      #       HOST=${{ vars.HOST }} 
+      #       PORT=${{ vars.PORT }} 
+      #       ELASTIC_URL=${{ vars.ELASTIC_URL }} 
+      #       ELASTIC_KEY=${{ vars.ELASTIC_KEY }}
+      #       IMAGE=${{ steps.push-image.outputs.image }}
 
-      - name: Deploy Amazon ECS task definition
-        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
-        id: ecs-deploy
-        with:
-          task-definition: ${{ steps.task-def.outputs.task-definition }}
-          service: ${{ env.ECS_SERVICE }}
-          cluster: ${{ env.ECS_CLUSTER }}
-          wait-for-service-stability: true
+      # - name: Deploy Amazon ECS task definition
+      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+      #   id: ecs-deploy
+      #   with:
+      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
+      #     service: ${{ env.ECS_SERVICE }}
+      #     cluster: ${{ env.ECS_CLUSTER }}
+      #     wait-for-service-stability: true
 
-      - name: Check if deployment was successful
-        id: check-deployment
-        run: |
-            CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query services[0].deployments[0].taskDefinition | jq -r ".")
-            NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
-            REVISION=${GITHUB_SHA::8}
-            echo "Current task arn: $CURRENT_TASK_DEF_ARN"
-            echo "New task arn: $NEW_TASK_DEF_ARN"
-            echo "Latest revision: $REVISION"
-            if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
-              echo "Deployment failed with latest code revision."
-              exit 1
-            else
-              echo "Deployment successfull."
-            fi
+      # - name: Check if deployment was successful
+      #   id: check-deployment
+      #   run: |
+      #       CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query services[0].deployments[0].taskDefinition | jq -r ".")
+      #       NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
+      #       REVISION=${GITHUB_SHA::8}
+      #       echo "Current task arn: $CURRENT_TASK_DEF_ARN"
+      #       echo "New task arn: $NEW_TASK_DEF_ARN"
+      #       echo "Latest revision: $REVISION"
+      #       if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
+      #         echo "Deployment failed with latest code revision."
+      #         exit 1
+      #       else
+      #         echo "Deployment successfull."
+      #       fi
 
-      - name: Publish JAR file to AWS CodeArtifact - generic
-        id: ca-deploy-generic
-        run: |
-          DOMAIN="testmvp-io"
-          DOMAIN_OWNER="704910415367"
-          CODE_ARTIFACT_REPO="java-maven-repo"
-          PACKAGE="ogcapi"
-          SOURCE_PATH="./server/target/server-java-1.0.0-SNAPSHOT-exec.jar"
-          CA_VERSION="1.0.3"
-          CA_NAMESPACE="ogcapi"
-          export ASSET_SHA256=$(sha256sum ./server/target/server-java-1.0.0-SNAPSHOT-exec.jar | awk '{print $1;}')
+      # - name: Publish JAR file to AWS CodeArtifact - generic
+      #   id: ca-deploy-generic
+      #   run: |
+      #     DOMAIN="testmvp-io"
+      #     DOMAIN_OWNER="704910415367"
+      #     CODE_ARTIFACT_REPO="java-maven-repo"
+      #     PACKAGE="ogcapi"
+      #     SOURCE_PATH="./server/target/server-java-1.0.0-SNAPSHOT-exec.jar"
+      #     CA_VERSION="1.0.3"
+      #     CA_NAMESPACE="ogcapi"
+      #     export ASSET_SHA256=$(sha256sum ./server/target/server-java-1.0.0-SNAPSHOT-exec.jar | awk '{print $1;}')
 
-          #aws codeartifact get-repository-endpoint --domain $DOMAIN --repository $CODE_ARTIFACT_REPO --format maven
-          #aws codeartifact login --tool pip --repository $CODE_ARTIFACT_REPO --domain $DOMAIN --domain-owner $DOMAIN_OWNER --region ${{ env.AWS_REGION }}
+      #     #aws codeartifact get-repository-endpoint --domain $DOMAIN --repository $CODE_ARTIFACT_REPO --format maven
+      #     #aws codeartifact login --tool pip --repository $CODE_ARTIFACT_REPO --domain $DOMAIN --domain-owner $DOMAIN_OWNER --region ${{ env.AWS_REGION }}
           
-          aws codeartifact publish-package-version --repository $CODE_ARTIFACT_REPO --domain $DOMAIN --domain-owner $DOMAIN_OWNER --format generic --package $PACKAGE --asset-content $SOURCE_PATH --package-version $CA_VERSION --asset-name $PACKAGE --asset-sha256 $ASSET_SHA256 --namespace $CA_NAMESPACE  --output text
+      #     aws codeartifact publish-package-version --repository $CODE_ARTIFACT_REPO --domain $DOMAIN --domain-owner $DOMAIN_OWNER --format generic --package $PACKAGE --asset-content $SOURCE_PATH --package-version $CA_VERSION --asset-name $PACKAGE --asset-sha256 $ASSET_SHA256 --namespace $CA_NAMESPACE  --output text
 
-          aws codeartifact list-package-versions --domain $DOMAIN --repository $CODE_ARTIFACT_REPO --format generic --package $PACKAGE --namespace $CA_NAMESPACE --output text
+      #     aws codeartifact list-package-versions --domain $DOMAIN --repository $CODE_ARTIFACT_REPO --format generic --package $PACKAGE --namespace $CA_NAMESPACE --output text
 
-          CURRENT_VERSION=$(aws codeartifact list-package-versions --domain $DOMAIN --repository $CODE_ARTIFACT_REPO --format generic --package $PACKAGE --namespace $CA_NAMESPACE --query defaultDisplayVersion | jq -r ".")
-          echo $CURRENT_VERSION
+      #     CURRENT_VERSION=$(aws codeartifact list-package-versions --domain $DOMAIN --repository $CODE_ARTIFACT_REPO --format generic --package $PACKAGE --namespace $CA_NAMESPACE --query defaultDisplayVersion | jq -r ".")
+      #     echo $CURRENT_VERSION
 
       - name: Publish JAR file to AWS CodeArtifact - maven
         id: ca-deploy-maven
@@ -228,11 +228,10 @@ jobs:
           SOURCE_PATH="./server/target/server-java-1.0.0-SNAPSHOT-exec.jar"
           CA_VERSION="1.0.0"
           CA_NAMESPACE="ogcapi-maven"
-          CA_URL="https://testmvp-io-704910415367.d.codeartifact.ap-southeast-2.amazonaws.com/maven/java-maven-repo/ogcapi-maven/1.0-SNAPSHOT/server-java-1.0.0-SNAPSHOT-exec.jar"
+          CA_URL="https://testmvp-io-704910415367.d.codeartifact.ap-southeast-2.amazonaws.com/java-maven-repo/ogcapi-maven/1.0-SNAPSHOT/server-java-1.0.0-SNAPSHOT-exec.jar"
           
           CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $DOMAIN --domain-owner $DOMAIN_OWNER --query authorizationToken --output text --duration-seconds 900)
-          
-          curl -X PUT -H "Content-Type: application/octet-stream" -H "Authorization: Bearer $CODEARTIFACT_AUTH_TOKEN" --upload-file $SOURCE_PATH $CA_URL
+
 
           
           
