build version test

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -40,12 +40,14 @@ jobs:
     steps:
       - name: Git clone the repository
         uses: actions/checkout@v3
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           role-to-assume: ${{ secrets.ROLE_ARN }}
           role-session-name: GitHub_to_AWS_via_FederatedOIDC
           aws-region: ${{ vars.AWS_REGION }}
+          
       # Hello from AWS: WhoAmI
       - name: Sts GetCallerIdentity
         run: |
@@ -115,7 +117,8 @@ jobs:
         id: prep
         run: |
           BRANCH=${GITHUB_REF##*/}
-          TS=$(date +%s)
+          TS=$(date +%F%H%M%S)
+          echo $TS | sed 's/-//g'
           REVISION=${GITHUB_SHA::8}
           BUILD_ID="${BRANCH}-${REVISION}-${TS}"
           LATEST_ID=canary
@@ -126,6 +129,32 @@ jobs:
           echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
           echo "LATEST_ID=$LATEST_ID"
           echo "BUILD_ID=$BUILD_ID" >> $GITHUB_OUTPUT
+
+      - name: Get and calculate latest package version - AWS CodeArtifact
+        id: ca-getversion
+        env:
+          BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}
+        run: |
+          FLAG_INITIAL=false
+          
+          CURRENT_VERSION=$(aws codeartifact list-package-versions --domain $CA_DOMAIN --repository $CA_REPO --format generic --package $CA_PACKAGE --namespace $CA_NAMESPACE --query defaultDisplayVersion | jq -r ".")
+          echo "current version: $CURRENT_VERSION"
+          
+          if [ -z "$CURRENT_VERSION" ]; then
+            CURRENT_VERSION="1.0.0"
+            FLAG_INITIAL=true
+          fi
+          IFS='.' read -ra version_parts <<< "$CURRENT_VERSION"
+          MAJOR=${version_parts[0]}
+          MINOR=${version_parts[1]}
+          NEW_MINOR=$((MINOR + 1))
+          if [ "$FLAG_INITIAL" == "true" ]; then
+            NEW_MINOR="0"
+          fi
+          
+          #version format[major.minor.build_number] 
+          #build_number format{BRANCH}-${REVISION}-${TS}
+          echo "latest_version=v$MAJOR.$NEW_MINOR.${{ env.BUILD_ID }}" >> $GITHUB_OUTPUT
       
       - name: Set up JDK 17
         uses: actions/setup-java@v3
@@ -145,8 +174,7 @@ jobs:
       - name: Build and tag image
         id: build-image
         env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          IMAGE_TAG: ${{ steps.prep.outputs.BUILD_ID }}
+          IMAGE_TAG: ${{ steps.ca-getversion.outputs.latest_version }}
         run: |
           # build a docker container to be deployed to ecr-ecs.
           docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
@@ -166,51 +194,51 @@ jobs:
       - name: Push image to Amazon ECR
         id: push-image
         env:
-          IMAGE_TAG: ${{ steps.prep.outputs.BUILD_ID }}
+          IMAGE_TAG: ${{ steps.ca-getversion.outputs.latest_version }}
         run: |
           # push image to aws ecr
           docker push $ECR_REPOSITORY:$IMAGE_TAG
           echo "image=$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
 
-      # - name: Fill in the new image ID in the Amazon ECS task definition
-      #   id: task-def
-      #   uses: aws-actions/amazon-ecs-render-task-definition@v1
-      #   with:
-      #     task-definition: ${{ env.ECS_TASK_DEFINITION }}
-      #     container-name: ${{ env.CONTAINER_NAME }}
-      #     image: ${{ steps.push-image.outputs.image }}
-      #     environment-variables: |
-      #       ENVIRONMENT=${{ env.ENVIRONMENT }}
-      #       HOST=${{ vars.HOST }} 
-      #       PORT=${{ vars.PORT }} 
-      #       ELASTIC_URL=${{ vars.ELASTIC_URL }}
-      #       ELASTIC_KEY=${{ secrets.ELASTIC_KEY }} 
-      #       IMAGE=${{ steps.push-image.outputs.image }}
+      - name: Fill in the new image ID in the Amazon ECS task definition
+        id: task-def
+        uses: aws-actions/amazon-ecs-render-task-definition@v1
+        with:
+          task-definition: ${{ env.ECS_TASK_DEFINITION }}
+          container-name: ${{ env.CONTAINER_NAME }}
+          image: ${{ steps.push-image.outputs.image }}
+          environment-variables: |
+            ENVIRONMENT=${{ env.ENVIRONMENT }}
+            HOST=${{ vars.HOST }} 
+            PORT=${{ vars.PORT }} 
+            ELASTIC_URL=${{ vars.ELASTIC_URL }}
+            ELASTIC_KEY=${{ secrets.ELASTIC_KEY }} 
+            IMAGE=${{ steps.push-image.outputs.image }}
 
-      # - name: Deploy Amazon ECS task definition
-      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
-      #   id: ecs-deploy
-      #   with:
-      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
-      #     service: ${{ env.ECS_SERVICE }}
-      #     cluster: ${{ env.ECS_CLUSTER }}
-      #     wait-for-service-stability: true
+      - name: Deploy Amazon ECS task definition
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
+        id: ecs-deploy
+        with:
+          task-definition: ${{ steps.task-def.outputs.task-definition }}
+          service: ${{ env.ECS_SERVICE }}
+          cluster: ${{ env.ECS_CLUSTER }}
+          wait-for-service-stability: true
 
-      # - name: Check if deployment was successful
-      #   id: check-deployment
-      #   run: |
-      #       CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query services[0].deployments[0].taskDefinition | jq -r ".")
-      #       NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
-      #       REVISION=${GITHUB_SHA::8}
-      #       echo "Current task arn: $CURRENT_TASK_DEF_ARN"
-      #       echo "New task arn: $NEW_TASK_DEF_ARN"
-      #       echo "Latest revision: $REVISION"
-      #       if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
-      #         echo "Deployment failed with latest code revision."
-      #         exit 1
-      #       else
-      #         echo "Deployment successfull."
-      #       fi
+      - name: Check if deployment was successful
+        id: check-deployment
+        run: |
+            CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query services[0].deployments[0].taskDefinition | jq -r ".")
+            NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
+            REVISION=${GITHUB_SHA::8}
+            echo "Current task arn: $CURRENT_TASK_DEF_ARN"
+            echo "New task arn: $NEW_TASK_DEF_ARN"
+            echo "Latest revision: $REVISION"
+            if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
+              echo "Deployment failed with latest code revision."
+              exit 1
+            else
+              echo "Deployment successfull."
+            fi
 
       # - name: Get and calculate latest package version - AWS CodeArtifact
       #   id: ca-getversion
@@ -238,82 +266,23 @@ jobs:
       #     #build_number format{BRANCH}-${REVISION}-${TS}
       #     echo "latest_version=$MAJOR.$NEW_MINOR.${{ env.BUILD_ID }}" >> $GITHUB_OUTPUT
 
-      # - name: Publish JAR file - AWS CodeArtifact
-      #   id: ca-deploy
-      #   env:
-      #     CA_VERSION: ${{ steps.ca-getversion.outputs.latest_version }}
-      #   run: |
-      #     export ASSET_SHA256=$(sha256sum ${{ vars.CA_SOURCE_PATH }} | awk '{print $1;}')
-      #     #ASSET_SHA256:- This value is used as an integrity check to verify that the assetContent has not changed after it was originally sent or published.
+      - name: Publish JAR file - AWS CodeArtifact
+        id: ca-deploy
+        env:
+          CA_VERSION: ${{ steps.ca-getversion.outputs.latest_version }}
+        run: |
+          export ASSET_SHA256=$(sha256sum ${{ vars.CA_SOURCE_PATH }} | awk '{print $1;}')
+          #ASSET_SHA256:- This value is used as an integrity check to verify that the assetContent has not changed after it was originally sent or published.
           
-      #     aws codeartifact publish-package-version \
-      #     --repository $CA_REPO \
-      #     --domain $CA_DOMAIN \
-      #     --domain-owner $CA_DOMAIN_OWNER \
-      #     --format generic \
-      #     --package $CA_PACKAGE \
-      #     --asset-content ${{ vars.CA_SOURCE_PATH }} \
-      #     --package-version ${{ env.CA_VERSION }} \
-      #     --asset-name $CA_PACKAGE \
-      #     --asset-sha256 $ASSET_SHA256 \
-      #     --namespace $CA_NAMESPACE  \
-      #     --output text
-
-  deploy:
-    needs: build-publish
-    runs-on: ubuntu-latest
-    environment: development
-    steps:
-      - name: Git clone the repository
-        uses: actions/checkout@v3
-        
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ secrets.ROLE_ARN }}
-          role-session-name: GitHub_to_AWS_via_FederatedOIDC
-          aws-region: ${{ vars.AWS_REGION }}
-      
-          # Hello from AWS: WhoAmI
-      - name: Sts GetCallerIdentity
-        run: |
-          aws sts get-caller-identity 
-
-      - name: Fill in the new image ID in the Amazon ECS task definition
-        id: task-def
-        uses: aws-actions/amazon-ecs-render-task-definition@v1
-        with:
-          task-definition: ${{ env.ECS_TASK_DEFINITION }}
-          container-name: ${{ needs.build-publish.outputs.CONTAINER_NAME }}
-          image: ${{ needs.build-publish.outputs.IMAGE_TAG }}
-          environment-variables: |
-            HOST=${{ vars.HOST }} 
-            PORT=${{ vars.PORT }} 
-            ELASTIC_URL=${{ vars.ELASTIC_URL }}
-            ELASTIC_KEY=${{ secrets.ELASTIC_KEY }} 
-            IMAGE=${{ needs.build-publish.outputs.IMAGE_TAG }}
-
-      - name: Deploy Amazon ECS task definition
-        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
-        id: ecs-deploy
-        with:
-          task-definition: ${{ steps.task-def.outputs.task-definition }}
-          service: ${{ needs.build-publish.outputs.ECS_SERVICE }}
-          cluster: ${{ needs.build-publish.outputs.ECS_CLUSTER }}
-          wait-for-service-stability: true
-
-      - name: Check if deployment was successful
-        id: check-deployment
-        run: |
-            CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ needs.build-publish.outputs.ECS_CLUSTER }} --services ${{ needs.build-publish.outputs.ECS_SERVICE }} --query services[0].deployments[0].taskDefinition | jq -r ".")
-            NEW_TASK_DEF_ARN=${{ steps.ecs-deploy.outputs.task-definition-arn }}
-            REVISION=${GITHUB_SHA::8}
-            echo "Current task arn: $CURRENT_TASK_DEF_ARN"
-            echo "New task arn: $NEW_TASK_DEF_ARN"
-            echo "Latest revision: $REVISION"
-            if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
-              echo "Deployment failed with latest code revision."
-              exit 1
-            else
-              echo "Deployment successfull."
-            fi
+          aws codeartifact publish-package-version \
+          --repository $CA_REPO \
+          --domain $CA_DOMAIN \
+          --domain-owner $CA_DOMAIN_OWNER \
+          --format generic \
+          --package $CA_PACKAGE \
+          --asset-content ${{ vars.CA_SOURCE_PATH }} \
+          --package-version ${{ env.CA_VERSION }} \
+          --asset-name $CA_PACKAGE \
+          --asset-sha256 $ASSET_SHA256 \
+          --namespace $CA_NAMESPACE  \
+          --output text
